name: ci 
on:
  push:
    branches:
      - master 
      - main
  workflow_run:
    workflows: ["automerge"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-gen-files
      - run: mkdocs gh-deploy --force
